In [1]:
"""
Classification is supervised learning technique.
Recall we said there are two types of Machine Learning algorithms
             ML/DM Algorithms
             /           \
            /             \
Supervised(Labeled Data) Unsupervised(Unlabeled Data)
     /                             \
    /                               \
Classification(Discrete Label)    Clustering (KNN, Divisive, Density based)
Regression (Continuous Label)     Association Rule Mining
Naivee Bayes                      PCA                 
Artificial Neural Network         SVD
Support Vector Machines           DNN
Ensembled Methods  

Classification can be applied when our target variable/response variable or class label 
is categorical. For example:

Readings https://www.unite.ai/supervised-vs-unsupervised-learning/
"""

'\nClassification is supervised learning technique.\nRecall we said there are two types of Machine Learning algorithms\n             ML/DM Algorithms\n             /                       /             Supervised(Labeled Data) Unsupervised(Unlabeled Data)\n     /                                 /                               Classification(Discrete Label)    Clustering (KNN, Divisive, Density based)\nRegression (Continuous Label)     Association Rule Mining\nNaivee Bayes                      PCA                 \nArtificial Neural Network         SVD\nSupport Vector Machines           DNN\nEnsembled Methods  \n\nClassification can be applied when our target variable/response variable or class label \nis categorical. For example:\n\nReadings https://www.unite.ai/supervised-vs-unsupervised-learning/\n'

In [2]:
'''
Lets read our dataset
'''
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
import seaborn as sb
from sklearn import preprocessing
%matplotlib inline

In [3]:
df = pd.read_csv('AutismAdultData.csv')
df.head()

id  A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0   1         1         1         1         1         0         0         1   
1   2         1         1         0         1         0         0         0   
2   3         1         1         0         1         1         0         1   
3   4         1         1         0         1         0         0         1   
4   5         1         0         0         0         0         0         0   

   A8_Score  A9_Score  ...  gender       ethnicity jundice austim  \
0         1         0  ...       f  White-European      no     no   
1         1         0  ...       m          Latino      no    yes   
2         1         1  ...       m          Latino     yes    yes   
3         1         0  ...       f  White-European      no    yes   
4         1         0  ...       f               ?      no     no   

   contry_of_res used_app_before result     age_desc  relation Class/ASD  
0  United States              no      6  18 and more      Self        NO  
1         Brazil              no      5  18 and more      Self        NO  
2          Spain              no      8  18 and more    Parent       YES  
3  United States              no      6  18 and more      Self        NO  
4          Egypt              no      2  18 and more         ?        NO  

[5 rows x 22 columns]

In [4]:
"""
Attribute  	Type	Description 
Age 	Number 	Age in years 
Gender 	String 	Male or Female 
Ethnicity	String	List of common ethnicities in text format 
Born with jaundice	Boolean  (yes or no)	Whether the case was born with jaundice
Family member with PDD	Boolean  (yes or no)	Whether any immediate family member has a PDD 
Who is completing the test	String 	Parent, self, caregiver, medical staff, clinician ,etc.
Country of residence 	String	List of countries in text format
Used the screening app before 	Boolean  (yes or no)	Whether the user has used a screening app
Screening Method Type 	Integer (0,1,2,3)	The type of screening methods chosen based on age category (0=toddler, 1=child, 2= adolescent, 3= adult)
Question 1 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 2 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 3 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 4 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 5 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 6 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 7 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 8 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 9 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Question 10 Answer 	Binary (0, 1)	The answer code of the question based on the screening method used  
Screening Score 	Integer 	The final score obtained based on the scoring algorithm of the screening method used. This was computed in an automated manner
"""

'\nAttribute  \tType\tDescription \nAge \tNumber \tAge in years \nGender \tString \tMale or Female \nEthnicity\tString\tList of common ethnicities in text format \nBorn with jaundice\tBoolean  (yes or no)\tWhether the case was born with jaundice\nFamily member with PDD\tBoolean  (yes or no)\tWhether any immediate family member has a PDD \nWho is completing the test\tString \tParent, self, caregiver, medical staff, clinician ,etc.\nCountry of residence \tString\tList of countries in text format\nUsed the screening app before \tBoolean  (yes or no)\tWhether the user has used a screening app\nScreening Method Type \tInteger (0,1,2,3)\tThe type of screening methods chosen based on age category (0=toddler, 1=child, 2= adolescent, 3= adult)\nQuestion 1 Answer \tBinary (0, 1)\tThe answer code of the question based on the screening method used  \nQuestion 2 Answer \tBinary (0, 1)\tThe answer code of the question based on the screening method used  \nQuestion 3 Answer \tBinary (0, 1)\tThe answe

In [5]:
df.describe()

id    A1_Score    A2_Score    A3_Score    A4_Score    A5_Score  \
count  704.000000  704.000000  704.000000  704.000000  704.000000  704.000000   
mean   352.500000    0.721591    0.453125    0.457386    0.495739    0.498580   
std    203.371581    0.448535    0.498152    0.498535    0.500337    0.500353   
min      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%    176.750000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%    352.500000    1.000000    0.000000    0.000000    0.000000    0.000000   
75%    528.250000    1.000000    1.000000    1.000000    1.000000    1.000000   
max    704.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         A6_Score    A7_Score    A8_Score    A9_Score   A10_Score      result  
count  704.000000  704.000000  704.000000  704.000000  704.000000  704.000000  
mean     0.284091    0.417614    0.649148    0.323864    0.573864    4.875000  
std      0.451301    0.493516    0.477576    0.468281    0.494866    2.501493  
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000    3.000000  
50%      0.000000    0.000000    1.000000    0.000000    1.000000    4.000000  
75%      1.000000    1.000000    1.000000    1.000000    1.000000    7.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000   10.000000

In [6]:
"""
In this data we can eaisly see that "Class/ASD"=y is the Target attribute/response variable/ class label
Rest of attributes are possible Predictors=X
This means that X -> y 
Where X={A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,ethnicity,jundice,austim,contry_of_res,result,age_desc}
      y={Class/ASD}
As you can see that y has only two labels in it i.e. NO, YES it is classifictaion problem.
As there are only two class labels available it means its Binary classifictaion problem
* In this course we will learn only binary classification
Readings https://machinelearningmastery.com/types-of-classification-in-machine-learning/
"""

'\nIn this data we can eaisly see that "Class/ASD"=y is the Target attribute/response variable/ class label\nRest of attributes are possible Predictors=X\nThis means that X -> y \nWhere X={A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,ethnicity,jundice,austim,contry_of_res,result,age_desc}\n      y={Class/ASD}\nAs you can see that y has only two labels in it i.e. NO, YES it is classifictaion problem.\nAs there are only two class labels available it means its Binary classifictaion problem\n* In this course we will learn only binary classification\nReadings https://machinelearningmastery.com/types-of-classification-in-machine-learning/\n'

In [7]:
#ID is meaniingless , used_app_before has onlly NO values in it 90%, relation is meaningless 
df.drop(columns=["id","used_app_before","relation"], inplace=True)

In [8]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score age gender       ethnicity jundice austim  \
0         1         0          0  26      f  White-European      no     no   
1         1         0          1  24      m          Latino      no    yes   
2         1         1          1  27      m          Latino     yes    yes   
3         1         0          1  35      f  White-European      no    yes   
4         1         0          0  40      f               ?      no     no   

   contry_of_res  result     age_desc Class/ASD  
0  United States       6  18 and more        NO  
1         Brazil       5  18 and more        NO  
2          Spain       8  18 and more       YES  
3  United States       6  18 and more        NO  
4          Egypt       2  18 and more        NO

In [9]:
#Its rule of any data scinece task that there should not be two independent attributes corelated
df.drop(columns="result", inplace=True)

In [10]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score age gender       ethnicity jundice austim  \
0         1         0          0  26      f  White-European      no     no   
1         1         0          1  24      m          Latino      no    yes   
2         1         1          1  27      m          Latino     yes    yes   
3         1         0          1  35      f  White-European      no    yes   
4         1         0          0  40      f               ?      no     no   

   contry_of_res     age_desc Class/ASD  
0  United States  18 and more        NO  
1         Brazil  18 and more        NO  
2          Spain  18 and more       YES  
3  United States  18 and more        NO  
4          Egypt  18 and more        NO

In [11]:
df.shape

(704, 18)

In [12]:
#Lets see unique values in column age_desc
df["age_desc"].unique()

array(['18 and more'], dtype=object)

In [13]:
#age_desc also has only one value in it i.e. is 18 and more. lets drop it
df.drop(columns="age_desc", inplace=True)

In [14]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score age gender       ethnicity jundice austim  \
0         1         0          0  26      f  White-European      no     no   
1         1         0          1  24      m          Latino      no    yes   
2         1         1          1  27      m          Latino     yes    yes   
3         1         0          1  35      f  White-European      no    yes   
4         1         0          0  40      f               ?      no     no   

   contry_of_res Class/ASD  
0  United States        NO  
1         Brazil        NO  
2          Spain       YES  
3  United States        NO  
4          Egypt        NO

In [15]:
df.dropna()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         1         1         1         0         0         1   
1           1         1         0         1         0         0         0   
2           1         1         0         1         1         0         1   
3           1         1         0         1         0         0         1   
4           1         0         0         0         0         0         0   
5           1         1         1         1         1         0         1   
6           0         1         0         0         0         0         0   
7           1         1         1         1         0         0         0   
8           1         1         0         0         1         0         0   
9           1         1         1         1         0         1         1   
10          1         1         1         1         1         1         1   
11          0         1         0         1         1         1         1   
12          0         1         1         1         1         1         0   
13          1         0         0         0         0         0         1   
14          1         0         0         0         0         0         1   
15          1         1         0         1         1         0         0   
16          1         0         0         0         0         0         1   
17          0         0         0         0         0         0         0   
18          0         0         1         0         1         1         0   
19          0         0         0         0         0         0         1   
20          0         1         1         1         0         0         0   
21          0         0         0         0         0         0         0   
22          0         0         0         1         0         0         1   
23          0         0         0         0         0         0         0   
24          1         1         1         1         0         0         0   
25          0         1         1         0         0         0         0   
26          0         0         0         0         0         0         0   
27          0         0         0         0         0         0         0   
28          0         0         0         0         0         0         0   
29          0         1         1         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
674         1         1         0         0         1         1         0   
675         1         1         1         1         0         0         0   
676         1         1         0         0         0         0         1   
677         1         0         0         0         0         0         1   
678         1         1         1         1         1         0         0   
679         1         1         1         1         1         1         1   
680         1         1         1         1         1         1         1   
681         1         1         0         1         1         1         1   
682         1         1         0         0         0         0         0   
683         1         1         0         0         0         0         0   
684         1         0         1         0         0         0         0   
685         1         0         1         1         1         0         0   
686         1         0         0         0         1         0         1   
687         1         1         1         0         1         1         1   
688         1         0         1         1         1         1         1   
689         1         0         0         0         1         1         1   
690         0         0         0         0         1         0         0   
691         1         0         0         1         0         0         1   
692         1         1         1         0         1         1         1   
693         1         0         0         1         0         0         0   
6

In [16]:
df.loc[df['ethnicity'].isin(['?'])]

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
4           1         0         0         0         0         0         0   
12          0         1         1         1         1         1         0   
13          1         0         0         0         0         0         1   
14          1         0         0         0         0         0         1   
19          0         0         0         0         0         0         1   
20          0         1         1         1         0         0         0   
24          1         1         1         1         0         0         0   
25          0         1         1         0         0         0         0   
62          0         0         0         0         0         0         0   
79          1         1         0         0         0         0         0   
80          0         0         1         1         0         0         1   
81          1         0         0         0         0         0         1   
91          0         1         0         0         1         0         1   
216         1         0         0         0         0         0         1   
221         0         0         1         0         0         0         0   
238         0         1         0         0         0         0         0   
257         0         1         1         0         1         0         0   
270         1         0         1         1         1         1         0   
276         1         0         0         0         1         0         0   
277         1         1         0         0         0         0         0   
285         0         0         0         1         1         1         1   
306         1         0         0         1         1         0         1   
315         1         1         0         0         0         0         0   
324         1         0         0         0         0         0         0   
337         1         1         0         0         0         0         0   
338         1         0         1         0         0         0         1   
339         1         0         0         0         0         0         1   
340         1         0         1         1         0         0         1   
341         1         1         1         1         1         0         0   
342         1         0         1         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
423         0         1         0         1         0         0         0   
427         1         0         0         1         0         0         1   
428         0         0         0         0         1         0         1   
429         1         0         1         0         1         0         1   
432         1         0         0         1         1         0         0   
438         1         1         0         0         0         0         0   
453         0         0         1         1         1         0         0   
485         0         1         0         0         0         0         0   
505         1         0         1         0         1         0         1   
518         0         1         0         0         0         0         0   
527         0         0         0         0         1         0         0   
534         0         0         0         1         1         0         1   
535         0         1         0         0         1         0         0   
536         0         1         0         0         1         0         0   
537         0         1         0         0         1         1         0   
556         1         1         0         0         0         0         0   
564         0         1         0         0         1         1         0   
571         1         0         0         0         0         0         0   
572         1         0         0         1         0         0         0   
588         1         0         1         1         1         1         1   
5

In [17]:
df.loc[df.ethnicity == "?", "ethnicity"] = "Others"

In [18]:
df.loc[df['ethnicity'].isin(['?'])]

Empty DataFrame
Columns: [A1_Score, A2_Score, A3_Score, A4_Score, A5_Score, A6_Score, A7_Score, A8_Score, A9_Score, A10_Score, age, gender, ethnicity, jundice, austim, contry_of_res, Class/ASD]
Index: []

In [19]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score age gender       ethnicity jundice austim  \
0         1         0          0  26      f  White-European      no     no   
1         1         0          1  24      m          Latino      no    yes   
2         1         1          1  27      m          Latino     yes    yes   
3         1         0          1  35      f  White-European      no    yes   
4         1         0          0  40      f          Others      no     no   

   contry_of_res Class/ASD  
0  United States        NO  
1         Brazil        NO  
2          Spain       YES  
3  United States        NO  
4          Egypt        NO

In [20]:
df.dtypes

A1_Score          int64
A2_Score          int64
A3_Score          int64
A4_Score          int64
A5_Score          int64
A6_Score          int64
A7_Score          int64
A8_Score          int64
A9_Score          int64
A10_Score         int64
age              object
gender           object
ethnicity        object
jundice          object
austim           object
contry_of_res    object
Class/ASD        object
dtype: object

In [21]:
df.loc[df.age == "?", "age"] = "0"

In [22]:
df["age"]=df["age"].astype(str,inplace=True)

In [23]:
df["age"]=df["age"].astype(int,inplace=True)

In [24]:
df.dtypes

A1_Score          int64
A2_Score          int64
A3_Score          int64
A4_Score          int64
A5_Score          int64
A6_Score          int64
A7_Score          int64
A8_Score          int64
A9_Score          int64
A10_Score         int64
age               int64
gender           object
ethnicity        object
jundice          object
austim           object
contry_of_res    object
Class/ASD        object
dtype: object

In [25]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score  age gender       ethnicity jundice austim  \
0         1         0          0   26      f  White-European      no     no   
1         1         0          1   24      m          Latino      no    yes   
2         1         1          1   27      m          Latino     yes    yes   
3         1         0          1   35      f  White-European      no    yes   
4         1         0          0   40      f          Others      no     no   

   contry_of_res Class/ASD  
0  United States        NO  
1         Brazil        NO  
2          Spain       YES  
3  United States        NO  
4          Egypt        NO

In [26]:
df.age.unique()

array([ 26,  24,  27,  35,  40,  36,  17,  64,  29,  33,  18,  31,  30,
        34,  38,  42,  43,  48,  37,  55,  50,  53,  20,  28,  21, 383,
        47,  32,  44,   0,  19,  58,  45,  22,  39,  25,  23,  54,  60,
        41,  46,  56,  61,  59,  52,  49,  51])

In [27]:
df.corr()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  \
A1_Score   1.000000  0.011539  0.074096  0.127814  0.169369  0.110199   
A2_Score   0.011539  1.000000  0.223921  0.158998  0.153821  0.185864   
A3_Score   0.074096  0.223921  1.000000  0.412722  0.264927  0.268846   
A4_Score   0.127814  0.158998  0.412722  1.000000  0.306806  0.295152   
A5_Score   0.169369  0.153821  0.264927  0.306806  1.000000  0.392354   
A6_Score   0.110199  0.185864  0.268846  0.295152  0.392354  1.000000   
A7_Score   0.217538 -0.041768  0.078216  0.151236  0.238589  0.175489   
A8_Score   0.147640  0.035408  0.017771  0.008617  0.102086  0.100123   
A9_Score   0.145452  0.205421  0.315113  0.327673  0.396582  0.479422   
A10_Score  0.118413  0.068883  0.168454  0.210968  0.267561  0.294435   
age        0.031077  0.020218  0.034015  0.037400 -0.024960  0.037739   

           A7_Score  A8_Score  A9_Score  A10_Score       age  
A1_Score   0.217538  0.147640  0.145452   0.118413  0.031077  
A2_Score  -0.041768  0.035408  0.205421   0.068883  0.020218  
A3_Score   0.078216  0.017771  0.315113   0.168454  0.034015  
A4_Score   0.151236  0.008617  0.327673   0.210968  0.037400  
A5_Score   0.238589  0.102086  0.396582   0.267561 -0.024960  
A6_Score   0.175489  0.100123  0.479422   0.294435  0.037739  
A7_Score   1.000000  0.085403  0.189480   0.252107 -0.027224  
A8_Score   0.085403  1.000000  0.101733   0.100782 -0.072924  
A9_Score   0.189480  0.101733  1.000000   0.283340  0.057249  
A10_Score  0.252107  0.100782  0.283340   1.000000 -0.007275  
age       -0.027224 -0.072924  0.057249  -0.007275  1.000000

In [28]:
#sb.pairplot(df, hue = 'Class/ASD')

In [29]:
X = df.iloc[:, :-1].values

In [30]:
#Lets get all other attributes beside class label/target attribute out of dataframe 
X

array([[1, 1, 1, ..., 'no', 'no', 'United States'],
       [1, 1, 0, ..., 'no', 'yes', 'Brazil'],
       [1, 1, 0, ..., 'yes', 'yes', 'Spain'],
       ...,
       [1, 0, 1, ..., 'no', 'no', 'Russia'],
       [1, 0, 0, ..., 'no', 'no', 'Pakistan'],
       [1, 0, 1, ..., 'no', 'no', 'Cyprus']], dtype=object)

In [31]:
#lets get the class label/target attribute out of DataFrame
y = df.iloc[:, -1].values

In [32]:
y

array(['NO', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'YES',
       'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES',
       'NO', 'YES', 'YES', 'NO', 'NO', 'NO', 'YES', 'YES', 'YES', 'NO',
       'NO', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES',
       'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES',
       'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'YES',
       'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO',
       'YES', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO',
       'YES', 'YES', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES',
       'YES', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'

In [33]:
#Converting our class label into binary value
#Readings https://towardsdatascience.com/categorical-encoding-using-label-encoding-and-one-hot-encoder-911ef77fb5bd
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0
 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1
 0 0 0 1 1 1 0 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 1 0 0 1 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 1
 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1
 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 0 0 1 0 0 

In [34]:
y.shape

(704,)

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
#Lets convert gender in term of one hot encoding 
#Readings https://towardsdatascience.com/categorical-encoding-using-label-encoding-and-one-hot-encoder-911ef77fb5bd
gender = OneHotEncoder().fit_transform(df[['gender']]).toarray()

In [37]:
#Lets see how gender looks after one hot encoded
gender

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [38]:
gender.shape

(704, 2)

In [39]:
genderDF=pd.DataFrame(gender).astype(int)

In [40]:
genderDF

0  1
0    1  0
1    0  1
2    0  1
3    1  0
4    1  0
5    0  1
6    1  0
7    0  1
8    0  1
9    0  1
10   0  1
11   1  0
12   1  0
13   0  1
14   1  0
15   0  1
16   0  1
17   0  1
18   1  0
19   0  1
20   0  1
21   1  0
22   0  1
23   0  1
24   0  1
25   1  0
26   0  1
27   0  1
28   0  1
29   0  1
..  .. ..
674  1  0
675  1  0
676  0  1
677  0  1
678  1  0
679  0  1
680  0  1
681  1  0
682  0  1
683  1  0
684  0  1
685  0  1
686  0  1
687  0  1
688  0  1
689  1  0
690  1  0
691  0  1
692  0  1
693  1  0
694  0  1
695  0  1
696  0  1
697  1  0
698  1  0
699  1  0
700  0  1
701  1  0
702  0  1
703  1  0

[704 rows x 2 columns]

In [41]:
#Lets convert rest of attributes/predictors in term of one hot encoding 
eth = OneHotEncoder().fit_transform(df[['ethnicity']]).toarray()
jund = OneHotEncoder().fit_transform(df[['jundice']]).toarray()
at = OneHotEncoder().fit_transform(df[['austim']]).toarray()
ctre= OneHotEncoder().fit_transform(df[['contry_of_res']]).toarray()

#Lets drop all original columns that are one hot encoded
df.drop(columns=['gender','ethnicity','jundice','austim','contry_of_res','Class/ASD'],inplace=True)

In [42]:
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score  age  
0         1         0          0   26  
1         1         0          1   24  
2         1         1          1   27  
3         1         0          1   35  
4         1         0          0   40

In [43]:
df.dtypes

A1_Score     int64
A2_Score     int64
A3_Score     int64
A4_Score     int64
A5_Score     int64
A6_Score     int64
A7_Score     int64
A8_Score     int64
A9_Score     int64
A10_Score    int64
age          int64
dtype: object

In [44]:
#Lets convert all one hot encoded columns from Numpy Array to Data Frame
eDF=pd.DataFrame(eth).astype(int)
jDF=pd.DataFrame(jund).astype(int)
aDF=pd.DataFrame(at).astype(int)
cDF=pd.DataFrame(ctre).astype(int)

In [45]:
#Lets combine all the datframe to retrive original X dataFrame or dataframe of all predictors
oneDF=pd.concat([df,genderDF, eDF,jDF,aDF,cDF], axis=1)

In [46]:
oneDF

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         1         1         1         0         0         1   
1           1         1         0         1         0         0         0   
2           1         1         0         1         1         0         1   
3           1         1         0         1         0         0         1   
4           1         0         0         0         0         0         0   
5           1         1         1         1         1         0         1   
6           0         1         0         0         0         0         0   
7           1         1         1         1         0         0         0   
8           1         1         0         0         1         0         0   
9           1         1         1         1         0         1         1   
10          1         1         1         1         1         1         1   
11          0         1         0         1         1         1         1   
12          0         1         1         1         1         1         0   
13          1         0         0         0         0         0         1   
14          1         0         0         0         0         0         1   
15          1         1         0         1         1         0         0   
16          1         0         0         0         0         0         1   
17          0         0         0         0         0         0         0   
18          0         0         1         0         1         1         0   
19          0         0         0         0         0         0         1   
20          0         1         1         1         0         0         0   
21          0         0         0         0         0         0         0   
22          0         0         0         1         0         0         1   
23          0         0         0         0         0         0         0   
24          1         1         1         1         0         0         0   
25          0         1         1         0         0         0         0   
26          0         0         0         0         0         0         0   
27          0         0         0         0         0         0         0   
28          0         0         0         0         0         0         0   
29          0         1         1         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
674         1         1         0         0         1         1         0   
675         1         1         1         1         0         0         0   
676         1         1         0         0         0         0         1   
677         1         0         0         0         0         0         1   
678         1         1         1         1         1         0         0   
679         1         1         1         1         1         1         1   
680         1         1         1         1         1         1         1   
681         1         1         0         1         1         1         1   
682         1         1         0         0         0         0         0   
683         1         1         0         0         0         0         0   
684         1         0         1         0         0         0         0   
685         1         0         1         1         1         0         0   
686         1         0         0         0         1         0         1   
687         1         1         1         0         1         1         1   
688         1         0         1         1         1         1         1   
689         1         0         0         0         1         1         1   
690         0         0         0         0         1         0         0   
691         1         0         0         1         0         0         1   
692         1         1         1         0         1         1         1   
693         1         0         0         1         0         0         0   
6

In [47]:
#We want to make sure that we will feed only inetger values/numeric to our model
oneDF.dtypes

A1_Score     int64
A2_Score     int64
A3_Score     int64
A4_Score     int64
A5_Score     int64
A6_Score     int64
A7_Score     int64
A8_Score     int64
A9_Score     int64
A10_Score    int64
age          int64
0            int64
1            int64
0            int64
1            int64
2            int64
3            int64
4            int64
5            int64
6            int64
7            int64
8            int64
9            int64
10           int64
0            int64
1            int64
0            int64
1            int64
0            int64
1            int64
             ...  
37           int64
38           int64
39           int64
40           int64
41           int64
42           int64
43           int64
44           int64
45           int64
46           int64
47           int64
48           int64
49           int64
50           int64
51           int64
52           int64
53           int64
54           int64
55           int64
56           int64
57           int64
58          

In [48]:
X=oneDF.values

In [49]:
"""
Dividing your data into test and train set is known as smapling. Here are types of sampling:
1- Random sampling
2- Smapling with replacement
3- Sampling without replacement
4- Stratified Sampling

Readings https://www.questionpro.com/blog/types-of-sampling-for-social-research/
"""

'\nDividing your data into test and train set is known as smapling. Here are types of sampling:\n1- Random sampling\n2- Smapling with replacement\n3- Sampling without replacement\n4- Stratified Sampling\n\nReadings https://www.questionpro.com/blog/types-of-sampling-for-social-research/\n'

In [50]:
#Train Test Split (It is called smapling)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (563, 95) (563,)
Test set: (141, 95) (141,)


In [51]:
#Just want to look how my class labels look in Training set
y_train

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [52]:
#Just want to see how my Training dataset look excluding class label
X_train

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [53]:
#We are using tree based classifier for model building
#Reference reading:https://scikit-learn.org/stable/modules/tree.html
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [54]:
y_predict=clf.predict(X_test)

In [55]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1])

In [56]:
#Accuracy evaluation
#Rference reading https://www.kdnuggets.com/2020/05/model-evaluation-metrics-machine-learning.html
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, clf.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, y_predict))

Train set Accuracy:  1.0
Test set Accuracy:  0.9078014184397163


In [57]:
#Confusion matrix is another handy evaluation of model
#Readings https://towardsdatascience.com/the-5-classification-evaluation-metrics-you-must-know-aa97784ff226

from sklearn.metrics import confusion_matrix
labels=[0,1]
cm=confusion_matrix(y_test,y_predict,labels)
print(cm)

[[95  8]
 [ 5 33]]


In [58]:
"""
Confusion matrix:
            Actual 0.  Actual 1
Predicted 0 [94          9]
Predicted 1 [ 5         33]

Accuracy= [Predicted 0 and Actual 0] # + [Predicted 1 and Actual 1] # / Total popullation
        = 94+33/139
Error= [Predicted 1 but Actual 0] # + [Predicted 0 and Actual 1] # / Total popullation
     = 5+9/139
Precision= [Predicted 0 and Actual 0]/[Predicted 0 and Actual 0]+[Predicted 0 and Actual 1]
         = 94/94+9
Recall= [Predicted 0 and Actual 0]/[Predicted 0 and Actual 0]+[Predicted 1 and Actual 0]
      = 94/94+5
Type I error= [Predicted 0 and Actual 1]= 9
Type II error= [Predicted 1 and Actual 0]=5
"""

'\n            Actual 0.  Actual 1\nPredicted 0 [94          9]\nPredicted 1 [ 5         33]\n\nAccuracy= [Predicted 0 and Actual 0] # + [Predicted 1 and Actual 1] # / Total popullation\n        = 94+33/139\nError= [Predicted 1 but Actual 0] # + [Predicted 0 and Actual 1] # / Total popullation\n     = 5+9/139\nPrecision= [Predicted 0 and Actual 0]/[Predicted 0 and Actual 0]+[Predicted 0 and Actual 1]\n         = 94/94+9\nRecall= [Predicted 0 and Actual 0]/[Predicted 0 and Actual 0]+[Predicted 1 and Actual 0]\n      = 94/94+5\nType I error= [Predicted 0 and Actual 1]= 9\nType II error= [Predicted 1 and Actual 0]=5\n'

In [59]:
#K nearest neighbor (K-NN) based classifier
#Readings https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
#REadings https://towardsdatascience.com/machine-learning-basics-with-the-k-nearest-neighbors-algorithm-6a6e71d01761

from sklearn.neighbors import KNeighborsClassifier
k = 4
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [60]:
#Predicting
yhat = neigh.predict(X_test)
yhat[0:5]

array([0, 0, 0, 0, 0])

In [61]:
#Accuracy evaluation
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.9289520426287744
Test set Accuracy:  0.9219858156028369


In [62]:
#Confusion matrix is another handy evaluation of model
from sklearn.metrics import confusion_matrix
labels=[0,1]
cm=confusion_matrix(y_test,yhat,labels)
print(cm)

[[99  4]
 [ 7 31]]
